[versions]
kotlin = "1.9.25"
spring-boot = "3.3.5"
dependency-management = "1.1.6"
telegram-bots = "6.9.7.1"
gson = "2.11.0"
mockk = "1.13.13"

[libraries]
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
spring-boot-starter-telegram-bots = { group = "org.telegram", name = "telegrambots-spring-boot-starter", version.ref = "telegram-bots" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
kotlin-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
postgresql = { group = "org.postgresql", name = "postgresql" }
liquibase = { group = "org.liquibase", name = "liquibase-core" }
h2 = { group = "com.h2database", name = "h2" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "dependency-management" }
kotlin-plugin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }